package com.example.wardrobe;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;

import java.util.ArrayList;
import java.util.List;

public class HomeActivity extends AppCompatActivity {
    List<Wardrobe> lstBook ;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);
        lstBook = new ArrayList<>();
       /*String a=getString(R.string.kids_boys_wear);
        String b=getString(R.string.kids_girls_wear);
        String c=getString(R.string.kids_summer_wear);
        String d=getString(R.string.boy_summer_wear);
        String e=getString(R.string.girl_summer_wear);
        String f=getString(R.string.mens_wear);
        String g=getString(R.string.womens_wear);
        String h=getString(R.string.mens_summer_wear);
        String i=getString(R.string.womens_summer_wear);
        String j=getString(R.string.mens_traditional_wear);
        String k=getString(R.string.womens_traditional_wear);
        String l=getString(R.string.toddler_boy_wear);
        String m=getString(R.string.toddler_girl_wear);
        String n=getString(R.string.vintage_men_wear);
        String o=getString(R.string.vintage_women_wear);*/
        lstBook.add(new Wardrobe("KIDS(BOY)","Categorie Book","Kids clothing is often more casual than adult clothing, fit for play and rest. Hosiery is commonly used. More recently, however, a lot of childrenswear is heavily influenced by trends in adult fashion. Due to the rise of social media platforms such as Instagram, celebrities and fashion bloggers have been using their accounts to post pictures of their children wearing luxury clothing, thus inspiring parents to dress their children as they would dress themselves. Good quality, well designed, garments are now a priority for a growing number of parents and children's clothing is getting a prime place in top label stores and high-end fashion retail outlets. Dresses are also getting separately designed for boys and girls at a very early age",R.drawable.kids_boys));
       lstBook.add(new Wardrobe("KIDS(GIRLS)","Categorie Book","Girl kids clothing is often more casual than adult clothing, fit for play and rest. Hosiery is commonly used. More recently, however, a lot of childrenswear is heavily influenced by trends in adult fashion. Due to the rise of social media platforms such as Instagram, celebrities and fashion bloggers have been using their accounts to post pictures of their children wearing luxury  clothing, thus inspiring parents to dress their children as they would dress themselves. Good quality, well designed, garments are now a priority for a growing number of parents and children's clothing is getting a prime place in top label stores and high-end fashion retail outlets. Dresses are also getting separately designed for boys and girls at a very early age",R.drawable.kids_girls));
        lstBook.add(new Wardrobe("KIDS SUMMER","Categorie Book","Cotton absorbs the sweat from your body and allows it to evaporate into the air. It works like a towel, wicking the moisture away from your skin and discouraging the growth of bacteria and yeast. This makes it the perfect fabric for summer, because it keeps you cool and prevents infections. You should avoid synthetic fabrics as much as possible, because unlike cotton and other natural fabrics, most synthetic fabrics do not breathe. So when you sweat, the sweat doesnt dry off like it should.",R.drawable.kids_summer));
        lstBook.add(new Wardrobe("KIDS SUMMER(BOYS)","Categorie Book","Cotton absorbs the sweat from your body and allows it to evaporate into the air. It works like a towel, wicking the moisture away from your skin and discouraging the growth of bacteria and yeast. This makes it the perfect fabric for summer, because it keeps you cool and prevents infections. You should avoid synthetic fabrics as much as possible, because unlike cotton and other natural fabrics, most synthetic fabrics do not breathe. So when you sweat, the sweat doesnt dry off like it should.",R.drawable.kids_boys_summer));
        lstBook.add(new Wardrobe("KIDS SUMMER(GIRLS)","Categorie Book","Cotton absorbs the sweat from your body and allows it to evaporate into the air. It works like a towel, wicking the moisture away from your skin and discouraging the growth of bacteria and yeast. This makes it the perfect fabric for summer, because it keeps you cool and prevents infections. You should avoid synthetic fabrics as much as possible, because unlike cotton and other natural fabrics, most synthetic fabrics do not breathe. So when you sweat, the sweat doesnt dry off like it should.",R.drawable.kids_girl_summer));
        lstBook.add(new Wardrobe("MENS WEAR","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.mens_wear));
        lstBook.add(new Wardrobe("WOMENS WEAR","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.womens_wear));
        lstBook.add(new Wardrobe("MENS SUMMER WEAR","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.mens_summer));
        lstBook.add(new Wardrobe("WOMENS SUMMER WEAR","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.summer_womens));
        lstBook.add(new Wardrobe("MENS TRADITIONAL","Categorie Book","Traditional dress may be defined as the ensemble of garments, jewelry, and accessories rooted in the past that is worn by an identifiable group of people. Though slight changes over time in color, form, and material are acknowledged, the assemblage seems to be handed down unchanged from the past. Traditional dress or costume is a phrase used widely both by the general public and writers on dress. It conjures up images of rural people dressed in colorful, layered, exotic clothing from an idealized past in some faraway place. This notion of traditional dress has been scrutinized and found inadequate by many researchers and scholars, but its uncritical use continues into the twenty-first century. The phrase traditional dress or costume is often used interchangeably with the terms ethnic, regional, and folk dress. For a concise discussion of this terminology see Welters and for a fascinating look at how the term is used try a Web search on the words \"traditional costume.\"",R.drawable.mens_traditional));
        lstBook.add(new Wardrobe("WOMENS TRADITIONAL","Categorie Book","Traditional dress may be defined as the ensemble of garments, jewelry, and accessories rooted in the past that is worn by an identifiable group of people. Though slight changes over time in color, form, and material are acknowledged, the assemblage seems to be handed down unchanged from the past. Traditional dress or costume is a phrase used widely both by the general public and writers on dress. It conjures up images of rural people dressed in colorful, layered, exotic clothing from an idealized past in some faraway place. This notion of traditional dress has been scrutinized and found inadequate by many researchers and scholars, but its uncritical use continues into the twenty-first century. The phrase traditional dress or costume is often used interchangeably with the terms ethnic, regional, and folk dress. For a concise discussion of this terminology see Welters and for a fascinating look at how the term is used try a Web search on the words \"traditional costume.\"",R.drawable.womens_traditional));
        lstBook.add(new Wardrobe("TODDLER(BOY)","Categorie Book","Infant and toddler clothing size is typically based on age.[1] These are usually preemie for a preterm birth baby, 0 to 3 months, 3 to 6 months, 6 to 9 months, 9 to 12 months, 12 months, 18 months, and 24 months, though there is no industry standard definition for those sizes.[1] Most retailers provide sizing charts based on a childs weight, height, or both, and the childs weight and height percentile may also be used for properly sizing clothing for the infant.[1]clothing and bedding interfere with normal exercise and growth and keep the baby from taking comfortable postures or changing posture during sleep.[2] An infant may stretch, necessitating clothing that is sufficiently loose to allow movement.",R.drawable.toddler_boy));
        lstBook.add(new Wardrobe("TODDLER(GIRLS)","Categorie Book","Infant and toddler clothing size is typically based on age.[1] These are usually preemie for a preterm birth baby, 0 to 3 months, 3 to 6 months, 6 to 9 months, 9 to 12 months, 12 months, 18 months, and 24 months, though there is no industry standard definition for those sizes.[1] Most retailers provide sizing charts based on a childs weight, height, or both, and the childs weight and height percentile may also be used for properly sizing clothing for the infant.[1]clothing and bedding interfere with normal exercise and growth and keep the baby from taking comfortable postures or changing posture during sleep.[2] An infant may stretch, necessitating clothing that is sufficiently loose to allow movement.",R.drawable.toddler_girl));
        lstBook.add(new Wardrobe("VINTAGE MEN","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.vintage_men));
        lstBook.add(new Wardrobe("VINTAGE WOMEN","Categorie Book","Vintage clothing is a generic term for garments originating from a previous era. The phrase is also used in connection with a retail outlet, e.g. in vintage clothing store. Today vintage dressing encompasses choosing accessories, mixing vintage garments with new, as well as creating an ensemble of various styles and periods.[1] Vintage clothes typically sell at low prices for high end named brands. It has been part of the world since World War I as an idea of reusing clothing because of the textile shortage.",R.drawable.vintage_women));

        RecyclerView myrv = (RecyclerView) findViewById(R.id.recyclerview_id);
        RecyclerViewAdapter myAdapter = new RecyclerViewAdapter(this,lstBook);
        myrv.setLayoutManager(new GridLayoutManager(this,3));
        myrv.setAdapter(myAdapter);

    }
}
